### PR TITLE
implement edit list functionality

### PR DESCRIPTION
**Pull request by allwelly**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change that updates code, but does not affect functionality)

# How Has This Been Tested?
- add item to list, press edit button and edit the text, the changes will be updated if you press the check button
- empty item will be reflected on the list, need to prevent users from adding empty items

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by lourw** [comment]
@allwelly can you run `flutter analyze` on your local machine and fix the linter errors

**Review by lourw — CHANGES_REQUESTED** [review]
Please split file so that there is one file per class

**Comment by lourw** [comment]
@mebesius how come the approval requirement was overriden here. Wait I just realized this PR isn't for merging into the main branch

**Comment by allwelly** [comment]
so for some reason the home.dart refers to TodoList() which is in todo_list.dart, with this in mind do we even need pages/todo.dart ?

**Comment by mebesius** [comment]
> @mebesius how come the approval requirement was overriden here. Wait I just realized this PR isn't for merging into the main branch

@lou-weng Yes, it's because it isn't for merging into main

**Comment by mebesius** [comment]
> so for some reason the home.dart refers to TodoList() which is in todo_list.dart, with this in mind do we even need pages/todo.dart ?

@allwelly That's because the `pages/todo.dart` file was moved from the `/pages` folder into `todo_list.dart`.  At least, it appears to have been a file rename from what I can tell. 

Since you are not attempting to merge into main and just into @MarkRWong 's to do list branch to start combining that code, it is fine. However, semantically speaking, if it is a page, it should be in the `/pages` folder and will need to be moved back into the `/pages` folder before being merged into main. You can choose to leave that for later once all of the to-do list functionality has been integrated with each other though. The widgets that you have defined that make up the to do list will need to be moved out of the `/flame` folder and into the `/widgets` folder (that exists on main but not in your current branch) at a later time as well.

**Pull request merged**
